openapi: 3.0.0
info:
  description: "This is the IPFS Pinning Service API. It attempts to be an  implementation-agnostic\
    \ API designed to be implemented by Pinning Service  Providers. \n\nThis specification\
    \ does **NOT** define the IPFS pinning API.\n\nGitHub discussion around this API\
    \ can be found in [ipfs/notes](https://github.com/ipfs/notes/issues/378).\n\n\n\
    **Critical Notice**\n\nTo allow backend systems behind the API to associate pins\
    \ with a particular  user, the API requires that a JSON Web Token is passed with\
    \ requests that  contains a `sub` claim (as specified by  [OpenIDConnect Standard\
    \ Claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims))\
    \ that represents the user's identity within the backend system, so as to  associate\
    \ the user with their pins. This allows the backend system to use  the identity\
    \ as a form of reference counting on pins, therefore only  removing pins once\
    \ no other users have it pinned."
  title: IPFS Pinning Service API
  version: 0.0.1
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/lanzafame/ipfs-pinning-service/v0.0.1
security:
- tokenAuth: []
paths:
  /pins:
    get:
      description: Get all the pins for the current user.
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PinStatus'
                type: array
          description: OK
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request (400)
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error (500)
      summary: Get all pins
      tags:
      - pins
    post:
      description: Add an array of pins for the current user.
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Pin'
              type: array
        required: true
      responses:
        202:
          description: Accepted
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request (400)
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized (401)
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found (404)
        409:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Insufficient Funds (409)
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error (500)
      summary: Add an array of pins
      tags:
      - pins
  /pins/{cid}:
    delete:
      description: Remove a Pin
      parameters:
      - explode: false
        in: path
        name: cid
        required: true
        schema:
          type: string
        style: simple
      responses:
        202:
          description: Accepted
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request (400)
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized (401)
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found (404)
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error (500)
      summary: Remove a Pin
      tags:
      - pins
    get:
      description: Get status of a Pin
      parameters:
      - explode: false
        in: path
        name: cid
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PinStatus'
          description: OK
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request (400)
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found (404)
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error (500)
      summary: Get status of a Pin
      tags:
      - pins
    post:
      description: If the parameters are valid, the server will return an 'Accepted'
        response. T
      parameters:
      - explode: false
        in: path
        name: cid
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: replication
        required: false
        schema:
          $ref: '#/components/schemas/ReplicationFactor'
        style: form
      - description: Associate metadata strings with a Pin.
        explode: true
        in: query
        name: meta
        required: false
        schema:
          $ref: '#/components/schemas/Metadata'
        style: form
      responses:
        202:
          description: Accepted
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request (400)
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized (401)
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found (404)
        409:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Insufficient Funds (409)
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error (500)
      summary: Add a new Pin
      tags:
      - pins
components:
  parameters:
    pinReplicationParam:
      explode: true
      in: query
      name: replication
      required: false
      schema:
        $ref: '#/components/schemas/ReplicationFactor'
      style: form
    pinMetaParam:
      description: Associate metadata strings with a Pin.
      explode: true
      in: query
      name: meta
      required: false
      schema:
        $ref: '#/components/schemas/Metadata'
      style: form
  responses:
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Bad Request (400)
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Unauthorized (401)
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The specified resource was not found (404)
    InsufficientFunds:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Insufficient Funds (409)
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Internal Server Error (500)
  schemas:
    Error:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    Cid:
      example:
        /: /
      properties:
        /:
          type: string
      type: object
    Metadata:
      additionalProperties:
        type: string
      type: object
    ReplicationFactor:
      minimum: -1
      type: integer
    PinStatus:
      example:
        peername: peername
        pin:
          replication: 0
          metadata:
            key: metadata
          cid:
            /: /
        peer: peer
        error: error
        status: status
        timestamp: timestamp
      properties:
        peername:
          type: string
        peer:
          type: string
        error:
          type: string
        pin:
          $ref: '#/components/schemas/Pin'
        status:
          type: string
        timestamp:
          type: string
      type: object
    Pin:
      example:
        replication: 0
        metadata:
          key: metadata
        cid:
          /: /
      properties:
        cid:
          $ref: '#/components/schemas/Cid'
        metadata:
          additionalProperties:
            type: string
          type: object
        replication:
          minimum: -1
          type: integer
      type: object
  securitySchemes:
    tokenAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
